version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: temp
      MYSQL_PASSWORD: temp
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql  # Verileri kalıcı hale getir

  python-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - mysql
    ports:
      - "5001:5000"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: