name: Docker Image CI

on:
  push:
    branches:
      - main  # Ana dalınıza göre ayarlayın

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: temp
          MYSQL_PASSWORD: temp
        ports:
          - 3306:3306
        volumes:
          - mysql_data:/var/lib/mysql

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./nginx/Dockerfile
        push: true
        tags: yourusername/nginx:latest
    - name: Build and push Python app
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./python/Dockerfile
        push: true
        tags: yourusername/python-app:latest

volumes:
  mysql_data:
